version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432" # Porta padrão do PostgreSQL
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
      POSTGRES_DB: devops
      POSTGRES_HOST_AUTH_METHOD: 'trust' # Configuração para permitir acesso de qualquer host
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # Mapeamento de volume para persistência dos dados do PostgreSQL
    networks:
      - stack

networks:
  stack:
